FROM openjdk:8u282-jre
EXPOSE 80/tcp
RUN apt-get update        
RUN apt-get install -y git
RUN mkdir /home/homework9      
RUN cd /home/homework9        
RUN git clone https://github.com/JamesAhlschwede/spring-petclinic.git
RUN cd ./spring-petclinic
RUN mvnw package
ENTRYPOINT ["java","-jar","./target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]